### ISSUE TITLE
How can I use this Threaded-VideoCapture with Django app

### ISSUE THREAD

**Issue by hardik0** [nup002/threaded-VideoCapture#2]
Hey @nup002 ,

Currently I'm using [this code](https://stackoverflow.com/a/49805833) for VideoCapture with Django webapp. So how can I replace with your solution?

Can please help I have tried but get only first frame then display is freeze.

**Comment by nup002** [comment]
Hi @hardik0 

To use `ThreadedVideoCapture` with the code in the example you linked, you can do the following:

```
import cv2
from threaded_videocapture import ThreadedVideoCapture
from django.http import StreamingHttpResponse


def gen(source):
    with ThreadedVideoCapture(source) as tvc:
        while True:
            ret, frame = tvc.read()
            if ret:
                _, jpeg = cv2.imencode('.jpg', frame)
                yield(b'--frame\r\n'
                      b'Content-Type: image/jpeg\r\n\r\n' + jpeg.tobytes() + b'\r\n\r\n')
            if ret is None:
                break

def livefe(request):
    return StreamingHttpResponse(0, content_type="multipart/x-mixed-replace;boundary=frame")
```

In this code, the generator `gen` itself creates the `ThreadedVideoCapture` object as a context manager in order to ensure that its thread is closed correctly when the django server quits.

I have tested and verified that this example works.

**Comment by hardik0** [comment]
This code is not applicable in my case but I have figure out something from your based code.

Thank you for your great code.
